version: "2"

checks:
    ### Disable checks for similar code ###
    ### Because this creates too many false positives ###

    similar-code: 
        enabled: false
    ### Increase the number of lines allowed for a method
    ### Becuase this is more reasonable fo Javascript

    method-lines:
        config:
            threshold: 50

exclude_patterns:
    - "**/tests/"
    - "**/spec/"
    - "**/*.spec.js"
    - "**/vendor/"
    - "**/node_modules/"
    - "**/media/"

coverage_directory: "./coverage/"