/* FILE USED FOR FRIEND DISPATCH TYPES */

// General Types
export const GET_FRIEND_START = 'GET_FRIEND_START'
export const GET_FRIEND_SUCCESS = 'GET_FRIEND_SUCCESS'
export const GET_FRIEND_FAIL = 'GET_FRIEND_FAIL'
export const GET_FRIEND_FAV_SHOP_START = 'GET_FRIEND_FAV_SHOP_START'
export const GET_FRIEND_FAV_SHOP_SUCCESS = 'GET_FRIEND_FAV_SHOP_SUCCESS'
export const GET_FRIEND_FAV_SHOP_FAIL = 'GET_FRIEND_FAV_SHOP_FAIL'

// Event Types
export const FRIEND_EVENT_START = 'FRIEND_EVENT_START'
export const FRIEND_EVENT_SUCCESS = 'FRIEND_EVENT_SUCCESS'
export const FRIEND_EVENT_FAIL = 'FRIEND_EVENT_FAIL'

//Review Types
export const FRIEND_REVIEW_START = 'FRIEND_REVIEW_START'
export const FRIEND_REVIEW_SUCCESS = 'FRIEND_REVIEW_SUCCESS'
export const FRIEND_REVIEW_FAIL = 'FRIEND_REVIEW_FAIL'

// Friends Types
export const GET_ALL_FRIENDS_START = 'GET_ALL_FRIENDS_START'
export const GET_ALL_FRIENDS_SUCCESS = 'GET_ALL_FRIENDS_SUCCESS'
export const GET_ALL_FRIENDS_FAIL = 'GET_ALL_FRIENDS_FAIL'