/* FILE USED FOR LOCATION DISPATCH TYPES */

// GENERAL TYPES
export const LOCATION_LOGIN_START = "LOCATION_LOGIN_START";
export const LOCATION_LOGIN_SUCCESS = "LOCATION_LOGIN_SUCCESS";
export const LOCATION_LOGIN_FAIL = "LOCATION_LOGIN_FAIL";
export const LOCATION_REGISTER_START = "LOCATION_REGISTER_START";
export const LOCATION_REGISTER_SUCCESS = "LOCATION_REGISTER_SUCCESS";
export const LOCATION_REGISTER_FAIL = "LOCATION_REGISTER_FAIL";
export const LOCATION_CLAIM_START = "LOCATION_CLAIM_START";
export const LOCATION_CLAIM_SUCCESS = "LOCATION_CLAIM_SUCCESS";
export const LOCATION_CLAIM_FAIL = "LOCATION_CLAIM_FAIL";
export const LOCATION_EVENTS_START = "LOCATION_EVENTS_START";
export const LOCATION_EVENTS_SUCCESS = "LOCATION_EVENTS_SUCCESS";
export const LOCATION_EVENTS_FAIL = "LOCATION_EVENTS_FAIL";
export const LOCATION_EVENTS_DELETE_START = "LOCATION_EVENTS_DELETE_START";
export const LOCATION_EVENTS_DELETE_SUCCESS = "LOCATION_EVENTS_DELETE_SUCCESS";
export const LOCATION_EVENTS_DELETE_FAIL = "LOCATION_EVENTS_DELETE_FAIL";
export const LOCATION_EVENTS_EDIT_SUCCESS = "LOCATION_EVENTS_EDIT_SUCCESS";
export const LOCATION_EVENTS_EDIT_FAIL = "LOCATION_EVENTS_EDIT_FAIL";
