/* FILE USED FOR USER DISPATCH TYPES */

// GENERAL TYPES
export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

// Settings
export const TOGGLE_EDIT = "TOGGLE_EDIT";
export const EDIT_SETTINGS = "EDIT_SETTINGS";
export const SUBMIT_SETTINGS_START = "SUBMIT_SETTINGS_START";
export const SUBMIT_SETTINGS_SUCCESS = "SUBMIT_SETTINGS_SUCCESS";
export const SUBMIT_SETTINGS_FAIL = "SUBMIT_SETTINGS_FAIL";
export const EDIT_CANCEL_CHANGES = "EDIT_CANCEL_CHANGES";
export const IMAGE_UPLOAD_START = "IMAGE_UPLOAD_START";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_FAIL = "IMAGE_UPLOAD_FAIL";
export const IMAGE_DELETE_START = "IMAGE_DELETE_START";
export const IMAGE_DELETE_SUCCESS = "IMAGE_DELETE_SUCCESS";
export const IMAGE_DELETE_FAIL = "IMAGE_DELETE_FAIL";
export const UPDATE_BIO_SUCCESS = "UPDATE_BIO_SUCCESS";

// USER REDUCER TYPES
export const USER_LOCATION_START = "USER_LOCATION_START";
export const USER_LOCATION_SUCCESS = "USER_LOCATION_SUCCESS";
export const USER_LOCATION_FAIL = "USER_LOCATION_FAIL";

// USER EVENT TYPES
export const USER_EVENT_START = "USER_EVENT_START";
export const USER_EVENT_SUCCESS = "USER_EVENT_SUCCESS";
export const USER_EVENT_FAIL = "USER_EVENT_FAIL";
export const USER_EVENT_DELETE_START = "USER_EVENT_DELETE_START";
export const USER_EVENT_DELETE_SUCCESS = "USER_EVENT_DELETE_SUCCESS";
export const USER_EVENT_DELETE_FAIL = "USER_EVENT_DELETE_FAIL";
export const USER_EVENT_EDIT_START = "USER_EVENT_EDIT_START";
export const USER_EVENT_EDIT_SUCCESS = "USER_EVENT_EDIT_SUCCESS";
export const USER_EVENT_EDIT_FAIL = "USER_EVENT_EDIT_FAIL";

// USER REVIEW TYPES
export const USER_REVIEW_START = "USER_REVIEW_START";
export const USER_REVIEW_SUCCESS = "USER_REVIEW_SUCCESS";
export const USER_REVIEW_FAIL = "USER_REVIEW_FAIL";
export const USER_REVIEW_DELETE_START = "USER_REVIEW_DELETE_START";
export const USER_REVIEW_DELETE_SUCCESS = "USER_REVIEW_DELETE_SUCCESS";
export const USER_REVIEW_DELETE_FAIL = "USER_REVIEW_DELETE_FAIL";
export const USER_REVIEW_EDIT_START = "USER_REVIEW_EDIT_START";
export const USER_REVIEW_EDIT_SUCCESS = "USER_REVIEW_EDIT_SUCCESS";
export const USER_REVIEW_EDIT_FAIL = "USER_REVIEW_EDIT_FAIL";

// USER FRIENDS

export const GET_USER_FRIENDS_START = "GET_USER_FRIENDS_START";
export const GET_USER_FRIENDS_SUCCESS = "GET_USER_FRIENDS_SUCCESS";
export const GET_USER_FRIENDS_FAIL = "GET_USER_FRIENDS_FAIL";

export const DELETE_USER_FRIENDS_START = "DELETE_USER_FRIENDS_START";
export const DELETE_USER_FRIENDS_SUCCESS = "DELETE_USER_FRIENDS_SUCCESS";
export const DELETE_USER_FRIENDS_FAIL = "DELETE_USER_FRIENDS_FAIL";
export const ADD_USER_FRIEND_START = "ADD_USER_FRIEND_START";
export const ADD_USER_FRIEND_SUCCESS = "ADD_USER_FRIEND_SUCCESS";
export const ADD_USER_FRIEND_FAIL = "ADD_USER_FRIEND_FAIL";

//USER PROMOS
export const GET_USER_PROMOS = "GET_USER_PROMOS";
export const ADD_USER_PROMOS = "ADD_USER_PROMOS";
