
export const GET_FRIEND_START = 'GET_FRIEND_START'
export const GET_FRIEND_SUCCESS = 'GET_FRIEND_SUCCESS'
export const GET_FRIEND_FAIL = 'GET_FRIEND_FAIL'
export const GET_FRIEND_FAV_SHOP_START = 'GET_FRIEND_FAV_SHOP_START'
export const GET_FRIEND_FAV_SHOP_SUCCESS = 'GET_FRIEND_FAV_SHOP_SUCCESS'
export const GET_FRIEND_FAV_SHOP_FAIL = 'GET_FRIEND_FAV_SHOP_FAIL'