/* FILE USED FOR DISPATCH TYPES */

// GENERAL TYPES
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// Settings
export const TOGGLE_EDIT = "TOGGLE_EDIT";
export const EDIT_SETTINGS = "EDIT_SETTINGS";
export const SUBMIT_SETTINGS_START = "SUBMIT_SETTINGS_START";
export const SUBMIT_SETTINGS_SUCCESS = "SUBMIT_SETTINGS_SUCCESS";
export const SUBMIT_SETTINGS_FAIL = "SUBMIT_SETTINGS_FAIL";
export const EDIT_CANCEL_CHANGES = "EDIT_CANCEL_CHANGES";
// USER REDUCER TYPES
export const USER_LOCATION_START = "USER_LOCATION_START";
export const USER_LOCATION_SUCCESS = "USER_LOCATION_SUCCESS";
export const USER_LOCATION_FAIL = "USER_LOCATION_FAIL";
export const USER_EVENT_SUCCESS = "USER_EVENT_SUCCESS";
export const USER_EVENT_FAIL = "USER_EVENT_FAIL";
export const USER_REVIEW_SUCCESS = "USER_REVIEW_SUCCESS";
